### ISSUE TITLE
Question about the training of MAGVIT-v2

### ISSUE THREAD

**Issue by RobertLuo1** [showlab/Show-o#22]
Hi, authors! Thanks for your great work! 
Here I would like to ask for some details of the pretraining of MAGVIT-v2. I see the codes include DinoV2(https://github.com/showlab/Show-o/blob/53cbe82bcda44f40c9e77c01c7f25fe75c055b66/models/common_modules.py#L360). I wonder if you choose it for the discriminator. Could you provide more details on the tokenizer training process?

Thank you in advance!

**Comment by Sierkinhane** [comment]
Hi, Robert, we didn't use the DINO features. We do not have a plan to release the training code of MAGVIT-v2 due to internal issues. Alternatively, you can take a look at this [repo](https://github.com/TencentARC/Open-MAGVIT2). All of us follow the training details provided in the MAGVIT-v2 paper. :)

**Comment by RobertLuo1** [comment]
Thanks for your quick reply. Could I know how you justify whether to finish the training or not?

**Comment by Sierkinhane** [comment]
Hi, reconstruction FID on ImageNet can help. Or empirically train it for 1000k/2000k iterations.

**Comment by RobertLuo1** [comment]
Thanks for your reply!
